### ISSUE TITLE
Make a Pull Request Template 

### ISSUE THREAD

**Issue by jeipollack** [CosmoStat/wf-psf#105]
This task is to make a Pull Request Template similar to the one in the [ShapePipe Repo](https://github.com/CosmoStat/shapepipe/blob/develop/.github/pull_request_template.md).

Add to the checklist a sentence about Validation Tests passing.
Add a section instructing where to copy the Validation Test Report.

It should be saved in the corresponding `.github` directory.
It should load automatically in the issue when someone opens a Pull Request.
Read more in this [Github Blog](https://github.blog/2016-02-17-issue-and-pull-request-templates/).

**Comment by jeipollack** [comment]
Updated description with the task of adding the Validation tests to the Pull Request Template.

**Comment by nadamoukaddem** [comment]
Is it possible to test if it opens automatically when someone creates a pull request before it is merged into the default branch?

**Comment by jeipollack** [comment]
you can fork the project to your GitHub repo and test there.

**Comment by jeipollack** [comment]
@sfarrens After my recent experience, I was thinking that it would be a good idea to require a minimum percentage in unit coverage of 70% for each PR.  

What do you think? Is this too strong a requirement and perhaps should be lowered to 60% or 50%?
