### ISSUE TITLE
Rename SimPSFToolkit.py module

### ISSUE THREAD

**Issue by jeipollack** [CosmoStat/wf-psf#112]
The module named `SimPSFToolkit` is too similar in name as the OU-SHE PSF code. This is bound to cause confusion (I was confused  when I first started).  I would like to propose changing the name of the module to something like PSFBuilder, PSFSimulator, etc.

**Comment by tobias-liaudat** [comment]
Sounds good to me, I like `PSFSimulator`

**Comment by jeipollack** [comment]
@nadamoukaddem can you open a new branch to change the name of the `SimPSFToolkit.py` module and class to `PSFSimulator`? Note, you have to update all package and class imports throughout the codebase including unit tests. Make sure to run tests to ensure no breaking behaviour.

**Comment by jeipollack** [comment]
Actually to follow PEP8 style rules, class names should be CapWords and module names should have short lower case names with underscores to improve readability.  So please rename the module: `psf_simulator.py` and use `PSFSimulator` for the class name. Thanks.
