### ISSUE TITLE
Add Code_of_Conduct, Contributions and WaveDiff_Dev_Workflow markdowns

### ISSUE THREAD

**Issue by jeipollack** [CosmoStat/wf-psf#114]
I prepared three Google Docs which should be converted to Markdown files:

* [CODE_OF_CONDUCT.md](https://docs.google.com/document/d/130iB4VN3TY2wZXcN7MxaqikgPDmaJbDjJfSDPRAj_Tw/edit)
* [CONTRIBUTING.md](https://docs.google.com/document/d/1bUPLYbMjlcUseE2gZOaC5pEGBNTvR2-4UV3XVbfgIwI/edit)
* [DEV_WORKFLOW.md](https://docs.google.com/document/d/1SJyAw7tEBRcJTa62SkU3qvjgoxrtoPbqRSEjaTIPQjA/edit)

Save the files in the top-level of the repo.

Update the documentation file: https://github.com/CosmoStat/wf-psf/blob/main/docs/source/index.rst?plain=1 by adding at the bottom:

```
Contributing
------------

For information on how to contribute to the development of WaveDiff, see
`Contributing to WaveDiff <./CONTRIBUTING.md>`_.
```

Make sure the links work.

**Comment by jeipollack** [comment]
Hi @nadamoukaddem I granted you edit access, but if there are changes you would like to propose please you suggest them instead of editing the document directly. Thanks

**Comment by nadamoukaddem** [comment]
Hi @jeipollack , should I include the last paragraph in [DEV_WORKFLOW.md](https://docs.google.com/document/d/1SJyAw7tEBRcJTa62SkU3qvjgoxrtoPbqRSEjaTIPQjA/edit) ?

**Comment by jeipollack** [comment]
> Hi @jeipollack , should I include the last paragraph in [DEV_WORKFLOW.md](https://docs.google.com/document/d/1SJyAw7tEBRcJTa62SkU3qvjgoxrtoPbqRSEjaTIPQjA/edit) ?

Hi @nadamoukaddem, thanks for catching this. Omit it from the new markdown file.

**Comment by nadamoukaddem** [comment]
Hi @jeipollack , I added the files and updated the documentation file, but when I opened the pull request, I didn't pass the test with pytest. I'm also having the same issue when running the tests on #112.
