### ISSUE TITLE
Link to Contribution markdown file incorrect in API Doc

### ISSUE THREAD

**Issue by jeipollack** [CosmoStat/wf-psf#127]
Tested API build with manual trigger and noticed the link to the Contribution markdown file is incorrect in the `index.rst` file.

**Comment by nadamoukaddem** [comment]
I couldn't find the link you mentioned. Could you please provide more details or point me in the right direction?

**Comment by jeipollack** [comment]
https://github.com/CosmoStat/wf-psf/blob/8186939e51a1bc2fa05a0e6bc830890b92170185/docs/source/index.rst?plain=1#L35

This was your addition that was pushed to `develop`.  The link is broken.

**Comment by nadamoukaddem** [comment]
I fixed the link.
