### ISSUE TITLE
Add support for custom multi-cycle training 

### ISSUE THREAD

**Issue by tobias-liaudat** [CosmoStat/wf-psf#25]
The training of the PSF model has only two options, using 1 or 2 cycles. The training script is hardcoded 😬 (please don't judge me). 

It would be nice to handle a custom number of cycles for the training script.

To do:
- [x] Modify the training script to handle `n` training cycles.
- [x] Check if the evaluation script needs to be modified as well. We need to indicate which model (generally the one from the last cycle) we will use to evaluate the performance metrics.
- [x] Handle the different learning rates and the number of epochs in the different epochs. Right now it is handled as a list of floats (or ints). The length of the list should be longer or equal to the number of cycles. Expected behaviour: If only one element is given in the list, use that number for all the cycles.
- [x] Maintain compatibility with the current usage of the scripts.
- [x] Define which model to save. We would like to save the model trained in the last cycle.
- [x] Modify the behaviour of `--saved_cycle` so that the default option is to use the last training cycle. The default should be `last` which would mean using the variable `total_cycles` to build the new `saved_cycle` parameter.

**Comment by CentofantiEze** [comment]
Multi-cycle feature added. PR will be created soon.

**Comment by tobias-liaudat** [comment]
@CentofantiEze The proper way to close the issue is with the PR that targets this issue :)
