### ISSUE TITLE
Add documentation for the general script in long-run folder

### ISSUE THREAD

**Issue by tobias-liaudat** [CosmoStat/wf-psf#28]
In the form of a `readme.md` file.

Explain how to use the script and what the parameters stand for.

Specify the inputs and outputs details.

**Comment by CentofantiEze** [comment]
The first has been done in a new [README](https://github.com/CentofantiEze/wf-psf/blob/feature-multi-cycle/long-runs/README.md) file.

The dataset and model predictions (I/O) will be detailed in a new file.

**Comment by CentofantiEze** [comment]
The input dataset is documented in the [Input_data.md](https://github.com/CentofantiEze/wf-psf/blob/feature-multi-cycle/long-runs/Input_data.md) file.
