### ISSUE TITLE
Metrics reproducibility problem in refactored code

### ISSUE THREAD

**Issue by tobias-liaudat** [CosmoStat/wf-psf#73]
I ran the metrics only evaluation using the [trained model](https://github.com/CosmoStat/wf-psf/tree/main/papers/article_IOP/data/models/wavediff-original) (chkp_callback_poly_sample_w_bis1_2k_cycle2) from the IOP paper, and using the same dataset ([train_Euclid_res_2000_TrainStars_id_001.npy](https://github.com/CosmoStat/wf-psf/blob/main/data/coherent_euclid_dataset/train_Euclid_res_2000_TrainStars_id_001.npy) for the training and [test_Euclid_res_id_001.npy](https://github.com/CosmoStat/wf-psf/blob/main/data/coherent_euclid_dataset/test_Euclid_res_id_001.npy) for the testing) found [here](https://github.com/CosmoStat/wf-psf/tree/main/data/coherent_euclid_dataset).

When running the metrics evaluation with this configuration, we should obtain the results from the IOP paper. This is not the case and we should investigate it.

The branch used to reproduce this problem is `refactor_config_runs` at [this commit](https://github.com/CosmoStat/wf-psf/tree/652bd8e69d67a119c8a29452f71b41e189749b96).

To launch the only metrics run, I copied the trained model into the refactored wavediff output format. I will attach a .zip file with the `wf-output` directory and the `config` directory I used to reproduce this issue.

[Archive.zip](https://github.com/CosmoStat/wf-psf/files/11959560/Archive.zip)

**Comment by jeipollack** [comment]
Hi @tobias-liaudat ,
  Here's the [notebook](https://github.com/CosmoStat/wf-psf/blob/bug_metrics_reproducibility_prob/main_metrics.ipynb) where I compare the metrics results (low-res) between the SED interpolation methods ([gen_SED_interp](https://github.com/CosmoStat/wf-psf/blob/899a6e36502b8ddc7af99dce04c30019c653bcf8/wf_psf/SimPSFToolkit.py#L688)
and [calc_SED_wave_values](https://github.com/CosmoStat/wf-psf/blob/899a6e36502b8ddc7af99dce04c30019c653bcf8/wf_psf/SimPSFToolkit.py#L903)  )
  
Reproduction of the paper results requires: 

- SED binning and interpolation function [gen_SED_interp](https://github.com/CosmoStat/wf-psf/blob/899a6e36502b8ddc7af99dce04c30019c653bcf8/wf_psf/SimPSFToolkit.py#L688)
- Generation of the GT stars from the model (and not the dataset)


I see that as long as the GT stars are generated from the model the results between new and old SED binning and interpolation methods are very close.  The difference is larger if the GT stars are used from the dataset.

**Comment by tobias-liaudat** [comment]
Thanks @jeipollack :) good to see those results. I think that the notebook you showed closes this issue. I'll let you close the issue if you also consider it as closed

**Comment by jeipollack** [comment]
Thanks for your help, @tobias-liaudat Tobias! I'll close this issue
