### ISSUE TITLE
Better handling of random seeds to assure full reproducibility

### ISSUE THREAD

**Issue by tobias-liaudat** [CosmoStat/wf-psf#75]

**Comment by sfarrens** [comment]
@tobias-liaudat is this something that would be relatively easy to hack, e.g. but inserting a random seed in to a specific module? It would be useful to be able to test this ASAP.

**Comment by tobias-liaudat** [comment]
@sfarrens I think it won't be hard to implement, we need to properly set the seeds for the initialisation of the layers and for the stochastic training. Maybe do a check if there's any other source of stochasticity, but for sure those two are the main ones. 
Right now, the noise is not generated on the fly and it's on the dataset so we could forget about that.

I thought of this as something in the ToDo list after the first release.

**Comment by jeipollack** [comment]
This has been achieved with the latest commit.
