### ISSUE TITLE
Update links to example configs in documentation

### ISSUE THREAD

**Issue by jeipollack** [CosmoStat/wf-psf#86]
Links to the example config files point in the [documentation](https://cosmostat.github.io/wf-psf/configuration.html) to the now deleted dummy-main branch.
[data_config.yaml](https://github.com/CosmoStat/wf-psf/blob/146725f2c2209bf3174c88c07a116e9ce28fff9a/docs/source/configuration.md?plain=1#L33)
[training_config.yaml](https://github.com/CosmoStat/wf-psf/blob/146725f2c2209bf3174c88c07a116e9ce28fff9a/docs/source/configuration.md?plain=1#L57)
[metrics_config.yaml](https://github.com/CosmoStat/wf-psf/blob/146725f2c2209bf3174c88c07a116e9ce28fff9a/docs/source/configuration.md?plain=1#L93l)
[plotting_config.yaml](https://github.com/CosmoStat/wf-psf/blob/146725f2c2209bf3174c88c07a116e9ce28fff9a/docs/source/configuration.md?plain=1#L216)

Update the links to point to correct config file in the `main` branch (see [here](https://github.com/CosmoStat/wf-psf/tree/main/config)).

**Comment by jeipollack** [comment]
I forgot this link is also broken: https://github.com/CosmoStat/wf-psf/blob/146725f2c2209bf3174c88c07a116e9ce28fff9a/docs/source/configuration.md?plain=1#L286

It should be replaced with this one: https://github.com/CosmoStat/wf-psf/blob/146725f2c2209bf3174c88c07a116e9ce28fff9a/config/configs.yaml

**Comment by nadamoukaddem** [comment]
In certain sections, there are missing links as illustrated below. These links need to be added ?

https://github.com/CosmoStat/wf-psf/blob/146725f2c2209bf3174c88c07a116e9ce28fff9a/docs/source/configuration.md?plain=1#L341
https://github.com/CosmoStat/wf-psf/blob/146725f2c2209bf3174c88c07a116e9ce28fff9a/docs/source/configuration.md?plain=1#L207
https://github.com/CosmoStat/wf-psf/blob/146725f2c2209bf3174c88c07a116e9ce28fff9a/docs/source/configuration.md?plain=1#L209

**Comment by jeipollack** [comment]
No. not from a commit state. You should add the links to the files in the main branch.
